version: '3'
services:
  qgis_lts:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile.test
      args:
        QGIS_TEST_VERSION: release-3_4
    tty: true
    environment:
      QGIS_TEST_VERSION: release-3_4
    volumes:
      - ${TRAVIS_BUILD_DIR}:/usr/src
  qgis_latest:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile.test
      args:
        QGIS_TEST_VERSION: latest
    tty: true
    environment:
      QGIS_TEST_VERSION: latest
    volumes:
      - ${TRAVIS_BUILD_DIR}:/usr/src
