version: '3'
services:
  qgis:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile.test
      args:
        QGIS_TEST_VERSION: ${QGIS_TEST_VERSION}
    tty: true
    volumes:
      - ${TRAVIS_BUILD_DIR}:/usr/src
